sudo: required

language: python
python:
  - 3.5

services:
  - docker

install:
  - docker build -t julienstroheker/dcos-autoscaler:latest .

script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi