sudo: required

services:
  - docker

before_install:
  - docker build -t julienstroheker/dcos-autoscaler:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi